version: '3.8'

services:
  chipi-web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    restart: unless-stopped

  # Opcional: Servicio para la IA (si se separa)
  chipi-ai:
    build:
      context: .
      dockerfile: Dockerfile.ai
    ports:
      - "8000:8000"
    environment:
      - CHIPI_API_KEY=${CHIPI_API_KEY}
    restart: unless-stopped